# Generated by Django 5.1.6 on 2025-02-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('SALE', 'Saída'), ('PURCHASE', 'Entrada'), ('ADJUSTMENT', 'Ajuste')], max_length=10),
        ),
    ]
