# Generated by Django 5.1.6 on 2025-02-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productinventory_product'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productinventory',
            constraint=models.UniqueConstraint(fields=('product',), name='unique_product_inventory'),
        ),
    ]
